name: 🛠 Tests-CI

on:
  pull_request:
  push:
    branches: [main]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

env:
  NODE_ENV: prod
  NODE_VERSION: '22'

jobs:
  checks:
    name: 🧪 Checks (lint, typecheck, test)
    runs-on: ubuntu-latest

    steps:
      - name: ⬇️ Checkout code
        uses: actions/checkout@v4

      - name: 📦 Install pnpm
        uses: pnpm/action-setup@v2

      - name: ⚙️ Setup Node ${{ env.NODE_VERSION }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: pnpm

      - name: 🔧 Install dependencies
        run: pnpm install --frozen-lockfile

      - name: 📖 Lint
        run: pnpm run lint

      - name: ☑️ Type checking
        run: pnpm run type:check

      - name: 🧪 Test
        run: pnpm run test

  build:
    name: 🏗 Build
    runs-on: ubuntu-latest

    steps:
      - name: ⬇️ Checkout code
        uses: actions/checkout@v4

      - name: 📦 Install pnpm
        uses: pnpm/action-setup@v2

      - name: ⚙️ Setup Node ${{ env.NODE_VERSION }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: pnpm

      - name: 🔧 Install dependencies
        run: pnpm install --frozen-lockfile

      - name: 🏗 Build
        run: pnpm run build
